import Header from "@/app/ui/molecules/Header";
import LoadingContent from "@/app/ui/molecules/LoadingContent";
import Sidebar from "@/app/ui/molecules/Sidebar";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <Header />
      <div className="flex w-full">
        <Sidebar />
        <main className="w-[82vw] p-6">{children}</main>
        <LoadingContent />
      </div>
    </>
  );
}
